services:

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: predict-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    container_name: predict-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped