FROM python:3.11-slim

WORKDIR /app

COPY /backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Usar variáveis de ambiente em vez do token diretamente
RUN wget -O /tmp/oneagent.sh \
  "https://${DT_TENANT}.live.dynatrace.com/api/v1/deployment/installer/agent/unix/default/latest?Api-Token=${DT_API_TOKEN}" \
  && sh /tmp/oneagent.sh --set-app-log-content-access=true

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]